/* this is the common layout for the entire application */

import "./utils/helpers/css/globals.css";
import Script from "next/script";
import useThirdPartyScripts from "./utils/custom-hooks/useThirdPartyScripts";
import { GoogleTagManager } from "@next/third-parties/google";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

/* for dynamic meta data generation */
// const generateMetaData = async ({ params }) => {
//     const { id, name } = params;

//     const data = await fetch(`https://.....${id}/${name}`).then((values) => {
//         return values;
//     });

//     return {
//         title: data.title,
//         description: data.description,
//     };
// };

const loadGTM = () => {
    const cbEnvironmentGTM = document.domain;
    const gtmScript = `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-TKDT3Z8');`;

    if (cbEnvironmentGTM === "localhost") {
        return `${gtmScript}&gtm_auth=3_0wnX23_A4RVlrHJTIqKg&gtm_preview=env-174&gtm_cookies_win=x`;
    } else if (cbEnvironmentGTM === "www.devcb.in" || cbEnvironmentGTM === "www.devstory.in") {
        return `${gtmScript}&gtm_auth=6MYUYYLvMg9Oo0hs70qQhA&gtm_preview=env-175&gtm_cookies_win=x`;
    }
    return gtmScript;
};

const RootLayout = ({ children }) => {
    const getThirdPartyScripts = useThirdPartyScripts();

    return (
        <html lang="en">
            <body>
                {/* Optimized GTM Script Loading */}
                <Script id="gtm" strategy="lazyOnload" dangerouslySetInnerHTML={{ __html: loadGTM() }} />

                {/* External Library - Lazy Loading */}
                <Script id="cdn-clouflare" strategy="lazyOnload" src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-md5/2.19.0/js/md5.min.js" />

                {/* Load Third-Party Scripts Dynamically */}
                {Object.keys(getThirdPartyScripts).map((key) => (
                    <Script key={key} id={key} strategy="lazyOnload" dangerouslySetInnerHTML={{ __html: getThirdPartyScripts[key] }} />
                ))}

                <h1>Common Layout</h1>
                {children}
            </body>
        </html>
    );
};

export default RootLayout;
