/* this is the common layout for the entire application */

import "./utils/helpers/css/globals.css";
import Script from "next/script";
import useThirdPartyScripts from "./utils/custom-hooks/useThirdPartyScripts";
import { GoogleTagManager } from "@next/third-parties/google";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

/* for dynamic meta data generation */
// const generateMetaData = async ({ params }) => {
//     const { id, name } = params;

//     const data = await fetch(`https://.....${id}/${name}`).then((values) => {
//         return values;
//     });

//     return {
//         title: data.title,
//         description: data.description,
//     };
// };

const RootLayout = ({ children }) => {
    const getThirdPartyScripts = useThirdPartyScripts();

    const layout = (
        // we have the html declaration here because this is the root of the application
        <html lang="en">
            <body>
                {/* Optimized GTM Script Loading */}
                {/* <Script id="gtm" strategy="lazyOnload" dangerouslySetInnerHTML={{ __html: loadGTM() }} /> */}

                {/* External Library - Lazy Loading */}
                <Script id="cdn-clouflare" strategy="lazyOnload" src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-md5/2.19.0/js/md5.min.js" />

                {/* Load Third-Party Scripts Dynamically */}
                {Object.keys(getThirdPartyScripts).map((key) => (
                    <Script key={key} id={key} strategy="lazyOnload" dangerouslySetInnerHTML={{ __html: getThirdPartyScripts[key] }} />
                ))}

                <h1>Common Layout</h1>
                {children}
            </body>
        </html>
    );

    return layout;
};

export default RootLayout;
